# Generated by Django 5.2.7 on 2026-02-24 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_chapter_branch_member_branch'),
    ]

    def migrate_data(apps, schema_editor):
        Position = apps.get_model('organization', 'Position')
        Member = apps.get_model('organization', 'Member')
        
        for member in Member.objects.all():
            if member.position:
                # El campo 'position' todavía es un CharField en este punto de la base de datos
                # pero el modelo en este estado podría estar confundido.
                # Usaremos RunSQL o manejaremos esto con cuidado.
                pass

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Cargo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['name'],
            },
        ),
        # 1. Creamos el campo temporal para no perder la data
        migrations.AddField(
            model_name='member',
            name='position_old',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo (Antiguo)'),
        ),
        # 2. Copiamos la data de 'position' a 'position_old' usando SQL directo
        # para evitar problemas con las definiciones de los modelos en Python
        migrations.RunSQL(
            "UPDATE organization_member SET position_old = position;",
            reverse_sql="UPDATE organization_member SET position = position_old;"
        ),
        # 3. Ahora sí podemos borrar el campo 'position' original (CharField)
        migrations.RemoveField(
            model_name='member',
            name='position',
        ),
        # 4. Creamos el nuevo campo 'position' (ForeignKey)
        migrations.AddField(
            model_name='member',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='organization.position', verbose_name='Cargo'),
        ),
        # 5. Opcional: Podríamos poblar 'position' desde 'position_old' aquí
        # Creamos los objetos Position únicos y los asociamos
    ]
