# Generated by Django 5.2.7 on 2026-02-24 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_position_member_position_old_alter_member_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='position_old',
        ),
    ]
