# Generated by Django 5.2.7 on 2026-02-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_alter_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='logo_file_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de logo ImageKit'),
        ),
        migrations.AddField(
            model_name='branch',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Logo ImageKit'),
        ),
        migrations.AddField(
            model_name='member',
            name='photo_file_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de foto ImageKit'),
        ),
        migrations.AddField(
            model_name='member',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Foto ImageKit'),
        ),
    ]
