# Generated by Django 5.2.7 on 2025-10-31 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('file', models.FileField(upload_to='resources/', verbose_name='Archivo')),
                ('category', models.CharField(choices=[('tutorial', 'Tutorial'), ('guide', 'Guía'), ('documentation', 'Documentación'), ('presentation', 'Presentación'), ('other', 'Otro')], max_length=20, verbose_name='Categoría')),
                ('download_count', models.IntegerField(default=0, verbose_name='Número de Descargas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to=settings.AUTH_USER_MODEL, verbose_name='Subido Por')),
            ],
            options={
                'verbose_name': 'Recurso Educativo',
                'verbose_name_plural': 'Recursos Educativos',
                'ordering': ['-created_at'],
            },
        ),
    ]
