# Generated by Django 5.2.7 on 2026-02-24 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_alter_member_email'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalresource',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='organization.chapter', verbose_name='Capítulo'),
        ),
    ]
