# Generated by Django 5.2.7 on 2026-02-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('announcement', 'Comunicado'), ('event', 'Evento'), ('achievement', 'Logro'), ('general', 'General')], default='general', max_length=20, verbose_name='Categoría'),
        ),
    ]
