# Generated by Django 5.2.7 on 2026-02-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_event_interested_users_alter_event_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_file_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de archivo ImageKit'),
        ),
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de ImageKit'),
        ),
        migrations.AddField(
            model_name='news',
            name='image_file_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de archivo ImageKit'),
        ),
        migrations.AddField(
            model_name='news',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de ImageKit'),
        ),
    ]
