# Generated by Django 5.2.7 on 2025-10-31 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('subject', models.CharField(max_length=300, verbose_name='Asunto')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leído')),
            ],
            options={
                'verbose_name': 'Formulario de Contacto',
                'verbose_name_plural': 'Formularios de Contacto',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50, verbose_name='Plataforma')),
                ('url', models.URLField(verbose_name='URL')),
                ('icon_url', models.URLField(blank=True, null=True, verbose_name='URL del Ícono')),
                ('display_order', models.IntegerField(default=0, verbose_name='Orden de Visualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Enlace Social',
                'verbose_name_plural': 'Enlaces Sociales',
                'ordering': ['display_order'],
            },
        ),
    ]
