# Generated by Django 5.2.7 on 2026-02-24 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_chapter_branch_member_branch'),
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='user',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='Biografía'),
        ),
        migrations.AddField(
            model_name='user',
            name='ieee_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IEEE ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='interested_chapters',
            field=models.ManyToManyField(blank=True, related_name='interested_users', to='organization.chapter', verbose_name='Capítulos de Interés'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
    ]
