# Generated by Django 5.2.7 on 2026-02-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_file_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de archivo ImageKit'),
        ),
    ]
