# Generated by Django 5.2.7 on 2026-02-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_avatar_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_file_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ImageKit File ID'),
        ),
    ]
